#!/bin/bash
backlight_dir=$(readlink -f "/sys/class/backlight/"$(ls /sys/class/backlight))
brightness_file="$backlight_dir/brightness"
min_brightness=0
max_brightness=$(cat "$backlight_dir/max_brightness")

set_raw_brightness() {
    if [ $1 -ge $min_brightness ] && [ $1 -le $max_brightness ]
    then
        sudo -n ls > /dev/null 2>&1
        if [ "$?" -ne "0" ] && [ "$UID" -ne "0" ]; then
            echo 'Root user privilege or passwordless sudo permission is required'
            exit
        fi
        sudo bash -c "echo $1 | tee $brightness_file"
    else
        echo "Invalid brightness value"
    fi
}

round() {
    base_round=$(echo "$1 / 1" | bc)
    diff=$(echo "($1 - $base_round) * 10" | bc)
    diff_round=$(echo "$diff / 1" | bc)
    if [ "$diff_round" -lt "5" ]
    then
        echo $base_round
    else
        echo $(echo "($1 + 1) / 1" | bc)
    fi
}

set_brightness() {
    new_brightness=$(get_percent $1 $max_brightness)
    set_raw_brightness $new_brightness
}

calculate_percent() {
    percent_f=$(echo "scale=2;$1 / $2 * 100" | bc)
    echo $(round $percent_f)
}

get_percent() {
    percent_f=$(echo "scale=2;$1 * $2 / 100" | bc)
    echo $(round $percent_f)
}

get_raw_brightness() {
    echo $(cat $brightness_file)
}

get_brightness() {
    raw_brightness=$(get_raw_brightness)
    echo $(calculate_percent $raw_brightness $max_brightness)
}


change_brightness() {
    case $1 in
        -inc)
            op='+'
            ;;
        -dec)
            op='-'
            ;;
    esac
    before=$(get_brightness)
    after=$(expr "$before" $op "$2")
    set_brightness $after
}

print_usage() {
    echo "Usage:
    -set <value>
    -inc <value>
    -dec <value>
    -get
    -raw_set <value>
    -raw_get"
}


if [ $# -eq 0 ]
then
    get_brightness
    exit
elif [ $# -eq 1 ]; then
    case $1 in
    -get)
        get_brightness
        ;;
    -raw_set)
        get_raw_brightness
        ;;
    *)
        print_usage
        ;;
    esac
elif [ $# -eq 2 ]
then
    case $1 in
        -set)
            set_brightness $2
            ;;
        -setr)
            set_raw_brightness $2
            ;;
        -inc|-dec)
            change_brightness $1 $2
            ;;
         -get)
            get_brightness
            ;;
        -raw_get)
            get_brightness
            ;;
        *)
            print_usage
            ;;
    esac
else
    print_usage
fi
