enable_audio_bell no

font_size 13.0
enabled_layouts tall:bias=75;full_size=1;mirrored=false,grid

map alt+shift+h move_window left
map alt+shift+l move_window right
map alt+shift+k move_window up
map alt+shift+j move_window down

map alt+a>x close_window
map alt+a>n launch --cwd=current
map alt+a>shift+n launch --type=tab --cwd=current
map alt+a>shift+o launch --type=os-window --cwd=current

map alt+a>r load_config_file

map ctrl+u scroll_page_up
map ctrl+d scroll_page_down
map ctrl+shift+j scroll_line_down
map ctrl+shift+k scroll_line_up

map alt+a>l next_tab
map alt+a>h previous_tab

map alt+a>shift+l next_layout


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME