#!/bin/bash

HDMI_STATUS=`cat /sys/class/drm/card0/card0-HDMI-A-1/status`

if [ $HDMI_STATUS = "connected" ]
then
  gnome-shell-extension-tool -d hidetopbar@mathieu.bidon.ca
else
  gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca
fi

