FROM archlinux:latest

# synchronize pacman databases ?
RUN pacman -Sy
# install base-devel package group
RUN pacman -S --needed --noconfirm base-devel

RUN useradd -m tarnas
# remove tarnas password (only for build)
RUN passwd -d tarnas
# add tarnas to sudoers
# FROM https://www.reddit.com/r/archlinux/comments/6qu4jt/how_to_run_makepkg_in_docker_container_yes_as_root/
RUN printf 'tarnas ALL=(ALL) ALL\n' | tee -a /etc/sudoers

# install utils
RUN pacman -S --needed --noconfirm git
RUN pacman -S --needed --noconfirm the_silver_searcher

# impersonate tarnas
USER tarnas
# create /builds directory
RUN cd /home/tarnas && mkdir builds

# OH-MY-ZSH
RUN cd /home/tarnas/builds && \
  git clone https://aur.archlinux.org/oh-my-zsh-git.git && \
  cd oh-my-zsh-git && \
  makepkg -sirc --noconfirm
RUN /usr/share/oh-my-zsh/tools/install.sh

# install asdf
RUN cd /home/tarnas/builds && \
  git clone https://aur.archlinux.org/asdf-vm.git && \
  cd asdf-vm && \
  makepkg -sirc --noconfirm

# NEOVIM (and dependencies)
USER root
RUN pacman -S --needed --noconfirm neovim
RUN pacman -S --needed --noconfirm python-neovim

# needed by YouCompleteMe
RUN pacman -S --needed --noconfirm cmake

USER tarnas
# # install vim-plug
RUN curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# used in vim-ranger
RUN cd /home/tarnas/builds && \
  git clone https://aur.archlinux.org/ranger-git.git && \
  cd ranger-git && \
  makepkg -sirc --noconfirm

# install default language runtimes via ASDF
RUN /bin/zsh -c ". /opt/asdf-vm/asdf.sh && \
  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git && \
  ${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring && \
  asdf install nodejs latest:12"
# full zsh inception with that global nodejs setting
RUN /bin/zsh -c ". /opt/asdf-vm/asdf.sh && \
  asdf global nodejs $(/bin/zsh -c '. /opt/asdf-vm/asdf.sh && asdf latest nodejs 12')"

# COPY CONFIGS AND INSTALL DEPENDENCIES
RUN cd /home/tarnas/ && mkdir .config
COPY --chown=tarnas:tarnas nvim /home/tarnas/.config/nvim
# can't use -es (silent), because it returns 1 for some reason
RUN nvim -u ~/.config/nvim/init.vim -i NONE -c "PlugInstall" -c "qa"
COPY --chown=tarnas:tarnas .gitconfig /home/tarnas/.gitconfig
COPY --chown=tarnas:tarnas .gitignore_global /home/tarnas/.gitignore_global
COPY --chown=tarnas:tarnas .zshrc /home/tarnas/.zshrc
# DIRTY FIX for .zshrc that assumes debian, this will stay here
# until we bite the bullet and have arch on host, as well xD
RUN sed -i 's/\$HOME\/\.asdf/\/opt\/asdf-vm/g' /home/tarnas/.zshrc

USER root
RUN usermod --shell /bin/zsh tarnas

# TODO install tmux ??

# remove tarnas from sudoers
# add sudo password for tarnas

RUN cd /home/tarnas && mkdir code
WORKDIR /home/tarnas/code
USER tarnas
CMD /bin/zsh
